{% raw %}{{- if and .Values.backend .Values.backend.enabled (not (default false .Values.backend.skip)) .Values.backend.autoscaling.enabled }}
{{- $hpaConfig := dict "Values" .Values -}}
{{- $_ := set $hpaConfig "Namespace" $.Release.Namespace -}}
{{- $_ := set $hpaConfig "ApplicationGroup" (default "app" .Values.project) -}}
{{- $_ := set $hpaConfig "Name" (default "backend" .Values.backend.image.name) -}}
{{- $_ := set $hpaConfig "ModuleValues" .Values.backend -}}
{{- $_ := set $hpaConfig "LabelData" "backend.pod.labels" -}}
{{ include "ag-template.hpa" $hpaConfig }}
{{- end }}
{% endraw %}