{% raw %}{{- if and .Values.backend .Values.backend.enabled (not (default false .Values.backend.skip)) }}
{{- $saConfig := dict "Values" .Values -}}
{{- $_ := set $saConfig "Namespace" $.Release.Namespace -}}
{{- $_ := set $saConfig "ApplicationGroup" (default "app" .Values.project) -}}
{{- $_ := set $saConfig "Name" (default "backend" .Values.backend.image.name) -}}
{{- $_ := set $saConfig "ModuleValues" .Values.backend -}}
{{- $_ := set $saConfig "LabelData" "backend.pod.labels" -}}
{{- $_ := set $saConfig "Labels" (dict "app.kubernetes.io/component" "backend") -}}
{{ include "ag-template.serviceaccount" $saConfig }}
{{- end }}
{% endraw %}
